apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-free-tier
  region: eu-west-3
  version: "1.30"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single   # Important pour outbound

managedNodeGroups:
  - name: free-tier-ng
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 30
    privateNetworking: false   # Public pour simplifier
    amiFamily: AmazonLinux2023

iam:
  withOIDC: true