apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor          
  namespace: monitoring
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app               
  
  namespaceSelector:
    matchNames:
      - flask-app                        
  
  endpoints:
  - port: http                     
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
